### PR TITLE
added tags feature for each question

### PR DESCRIPTION
**Pull request by rupak2001**
The changes are being made; now you can add tags directly on your questions. 
To do so: just add a field of tag on each of the questions in the data.js file (implemented on the first question).

Thank you

### CODE REVIEW

**Comment by MRIDUL-MB** [comment]
Can You share Screen Shot?
why did you change the yarn.lock file?

**Comment by rupak2001** [comment]
Screenshot from 2022-10-24 11-55-23

here you go

**Comment by rupak2001** [comment]
oops sorry, actually i am using linux, so when i ran "npm install", it got updated automatically.
I think you can run the same without any error or if you want i can undo that

**Comment by MRIDUL-MB** [comment]
Thanks:)

**Pull request merged**
